### ISSUE TITLE
Question about resources in code2seq

### ISSUE THREAD

**Issue by lishi0927** [tech-srl/code2seq#23]
Hello, I have a new question.
How much GPU memory is needed for training the network in code2seq with the default configurations?
I use tensorflow 1.15.0 with GTX 2080(8GB GPU memeory) in Ubuntu18.04, but still have the resource exhausted error.

```
2019-11-01 11:08:10.487546: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ****************************************************************************************************
2019-11-01 11:08:10.487564: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at matmul_op.cc:480 : Resource exhausted: OOM when allocating tensor with shape[102400,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[102400,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model/bidirectional_rnn/fw/fw/while/lstm_cell/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[model/Momentum/update/_224]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[102400,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node model/bidirectional_rnn/fw/fw/while/lstm_cell/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
```

**Comment by urialon** [comment]
Hi,
I trained it on a Tesla v100, which has 16gb.

If you want to train it yourself (rather than using our trained model) you can try decreasing the batch size by half.

Good luck!

**Comment by lishi0927** [comment]
Thank you for your reply.
I set the batch_size = 128, the GPU memory needs about 6971MB;
