### ISSUE TITLE
Error when running the program

### ISSUE THREAD

**Issue by liangxi11** [tech-srl/code2seq#31]
Hi, 
When I use command "bash train.sh", errors occurred.
I though it was because of the length of but I found they were less than 10.
I cannot find the reason. Can you tell me any possible reason causing this bug please?

Thx!

2020-01-08 23:11:19.264751: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-08 23:11:20.352762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: TITAN RTX major: 7 minor: 5 memoryClockRate(GHz): 1.77
pciBusID: 0000:09:00.0
totalMemory: 23.62GiB freeMemory: 14.38GiB
2020-01-08 23:11:20.352827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-01-08 23:11:21.006092: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-08 23:11:21.006192: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-01-08 23:11:21.006203: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-01-08 23:11:21.007392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 13914 MB memory) -> physical GPU (device: 0, name: TITAN RTX, pci bus id: 
0000:09:00.0, compute capability: 7.5)
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/sparse_ops.py:1165: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], [?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT
_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node model/dense/Tensordot/GatherV2/_183}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, 
tensor_name="edge_1720_model/dense/Tensordot/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
tensor_name="edge_1720_model/dense/Tensordot/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]                                                                                          [66/1655]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 95, in train
    _, batch_loss = self.sess.run([optimizer, train_loss])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: End of sequence
         [[node IteratorGetNext (defined at /home/lxr/baseline/code2seq/code2seq/reader.py:192)  = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], 
[?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node model/dense/Tensordot/GatherV2/_183}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, 
tensor_name="edge_1720_model/dense/Tensordot/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'IteratorGetNext', defined at:
  File "code2seq.py", line 36, in <module>
    model.train()
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 76, in train
    config=self.config)
  File "/home/lxr/baseline/code2seq/code2seq/reader.py", line 43, in __init__
    self.output_tensors = self.compute_output()
  File "/home/lxr/baseline/code2seq/code2seq/reader.py", line 192, in compute_output
    return self.iterator.get_next()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
         [[node IteratorGetNext (defined at /home/lxr/baseline/code2seq/code2seq/reader.py:192)  = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], 
[?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
         [[{{node model/dense/Tensordot/GatherV2/_183}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, 
tensor_name="edge_1720_model/dense/Tensordot/GatherV2", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 1001 fields but have more in record
         [[{{node IteratorGetNext_1}} = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], [?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, 
DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2_1)]]
         [[{{node model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1/_389}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", s
end_device_incarnation=1, tensor_name="edge_487_model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "code2seq.py", line 36, in <module>
    model.train()
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 106, in train
    results, precision, recall, f1 = self.evaluate()
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 184, in evaluate
    [self.eval_predicted_indices_op, self.eval_true_target_strings_op, self.eval_topk_values],
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expect 1001 fields but have more in record
         [[node IteratorGetNext_1 (defined at /home/lxr/baseline/code2seq/code2seq/reader.py:192)  = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], [?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2_1)]]
         [[{{node model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1/_389}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_487_model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'IteratorGetNext_1', defined at:
  File "code2seq.py", line 36, in <module>
    model.train()
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 106, in train
    results, precision, recall, f1 = self.evaluate()
  File "/home/lxr/baseline/code2seq/code2seq/model.py", line 148, in evaluate
    config=self.config, is_evaluating=True)
  File "/home/lxr/baseline/code2seq/code2seq/reader.py", line 43, in __init__
    self.output_tensors = self.compute_output()
  File "/home/lxr/baseline/code2seq/code2seq/reader.py", line 192, in compute_output
    return self.iterator.get_next()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 2069, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Expect 1001 fields but have more in record
         [[node IteratorGetNext_1 (defined at /home/lxr/baseline/code2seq/code2seq/reader.py:192)  = IteratorGetNext[output_shapes=[[?,160,11], [?,160], [?,160,5], [?,160], [?,160,1], [?,160,1], [?,160,5], [?,160], [?,160,1], [?,?], [?], [?], [?,160]], output_types=[DT_INT32, DT_INT32, DT_INT32, DT_INT32, DT_STRING, DT_STRING, DT_INT32, DT_INT32, DT_STRING, DT_INT32, DT_INT64, DT_STRING, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2_1)]]
         [[{{node model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1/_389}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_487_model_1/LuongAttention/memory_layer/Tensordot/GatherV2_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

**Comment by liangxi11** [comment]
Forgot to mention "I created the preprocessed data by[PathMiner](https://github.com/JetBrains-Research/astminer)".

**Comment by urialon** [comment]
Hi @liangxi11 ,
PathMiner is great but I have never worked with it so I am not sure about how exactly does it connect to code2seq.

The real problem here is this: `InvalidArgumentError (see above for traceback): Expect 1001 fields but have more in record`. 

Code2seq expects each line in the input to have 1001 space-delimited contexts (1 target sequence + 1000 paths). If there are less than 1001, the `preprocessing.py` script pads the line with extra spaces. If there are more than 1000, the preprocessing script truncates it.
I am guessing that PathMiner does only the step that is equivalent to JavaExtractor (i.e., only up to [this line](https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L51)), but then you need to run the next preprocessing steps that begin [here](https://github.com/tech-srl/code2seq/blob/master/preprocess.sh#L54).

Let me know how it goes.
Best,
Uri
