### ISSUE TITLE
Error while running train.sh on custom dataset

### ISSUE THREAD

**Issue by rishab-32** [tech-srl/code2seq#44]
Hi, when I run train.sh on preprocessed custom dataset (Done using preprocess.sh), I encounter the following error. Can you suggest the possible reason for such behavior?

Initalized variables
Started reader...
2020-05-03 22:34:30.310277: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
Average loss at batch 100: 25.005198, 	throughput: 343 samples/sec
Finished 1 epochs
WARNING:tensorflow:Entity <bound method Reader.process_dataset of <reader.Reader object at 0x7fb71eb9d7b8>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: module 'gast' has no attribute 'Num'
Done testing, epoch reached
Traceback (most recent call last):
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
	 [[model/gradients/model/embedding_lookup_2_grad/Size/_35]]
  (1) Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/code2seq/model.py", line 96, in train
    _, batch_loss = self.sess.run([optimizer, train_loss])
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: 2 root error(s) found.
  (0) Out of range: End of sequence
	 [[node IteratorGetNext (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[model/gradients/model/embedding_lookup_2_grad/Size/_35]]
  (1) Out of range: End of sequence
	 [[node IteratorGetNext (defined at /tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'IteratorGetNext':
  File "code2seq.py", line 39, in <module>
    model.train()
  File "/content/code2seq/model.py", line 77, in train
    config=self.config)
  File "/content/code2seq/reader.py", line 43, in __init__
    self.output_tensors = self.compute_output()
  File "/content/code2seq/reader.py", line 192, in compute_output
    return self.iterator.get_next()
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/data/ops/iterator_ops.py", line 426, in get_next
    name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/gen_dataset_ops.py", line 2518, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.2/python3.6/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2seq.py", line 39, in <module>
    model.train()
  File "/content/code2seq/model.py", line 108, in train
    results, precision, recall, f1, rouge = self.evaluate()
  File "/content/code2seq/model.py", line 228, in evaluate
    files_rouge = FilesRouge(predicted_file_name, ref_file_name)
  File "/content/code2seq/rouge/rouge.py", line 13, in __init__
    self.rouge = Rouge(*args, **kwargs)
  File "/content/code2seq/rouge/rouge.py", line 72, in __init__
    raise ValueError("Unknown metric '%s'" % m)
ValueError: Unknown metric 'm'

**Comment by urialon** [comment]
Hi @rishab-32 ,
Thank you for reporting this! I just pushed a fix. 
The error has occurred because we used an older API of the rouge library.

Let me know if it now works.
Best,
Uri

**Comment by rishab-32** [comment]
Hi @urialon ,
Thanks for the prompt update, now the model is training fine. If I have any more questions, I would contact you. Thanks for the wonderful repo and for maintaining it so well.

Best,
Rishab
