### ISSUE TITLE
Errors when creating new dataset.

### ISSUE THREAD

**Issue by JiyangZhang** [tech-srl/code2seq#46]
Hi, thanks for your code, I used your script to create a new data set. I first want to use a small set of 10 methods to run the model. But, when training it will have the following error. I found out that if I use the dict you provided, this error will not appear. Is it not recommended using very small dataset to run the model?

errors:

```
Started reader...
2020-05-05 15:52:51.484324: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
Traceback (most recent call last):
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expect 201 fields but have more in record
	 [[{{node IteratorGetNext}}]]
	 [[model/gradients/model/embedding_lookup_2_grad/Size/_33]]
  (1) Invalid argument: Expect 201 fields but have more in record
	 [[{{node IteratorGetNext}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2seq.py", line 39, in <module>
    model.train()
  File "/code2seq/model.py", line 96, in train
    _, batch_loss = self.sess.run([optimizer, train_loss])
  File "/hlib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "//lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Expect 201 fields but have more in record
	 [[node IteratorGetNext (defined at /home/jiyang/code/code2seq/reader.py:192) ]]
	 [[model/gradients/model/embedding_lookup_2_grad/Size/_33]]
  (1) Invalid argument: Expect 201 fields but have more in record
	 [[node IteratorGetNext (defined at /home/jiyang/code/code2seq/reader.py:192) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at /code2seq/reader.py:190)

Input Source operations connected to node IteratorGetNext:
 IteratorV2 (defined at /code2seq/reader.py:190)

Original stack trace for 'IteratorGetNext':
  File "code2seq.py", line 39, in <module>
    model.train()
  File code2seq/model.py", line 77, in train
    config=self.config)
  File "//code2seq/reader.py", line 43, in __init__
    self.output_tensors = self.compute_output()
  File "/code2seq/reader.py", line 192, in compute_output
    return self.iterator.get_next()
  File "//lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 426, in get_next
    output_shapes=self._structure._flat_shapes, name=name)
  File "//lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1947, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

```

**Comment by JiyangZhang** [comment]
Just curious about what results in the error

**Comment by urialon** [comment]
Hi @JiyangZhang ,
Thank you for your interest in code2seq!

I am aware that sometimes the reader tries to read a batch, and 10 examples are not even enough for a single batch.

But I think that in your case, the error is not even related to the number of examples, but to the number of paths ("contexts") in each example. The reader expects 201 fields, which are 1 target sequence and 200 contexts. Did you preprocess your data with other numbers than the defaults for `MAX_CONTEXTS` and `MAX_DATA_CONTEXTS`?

**Comment by JiyangZhang** [comment]
Hi @urialon ,

Thanks for the reply and that makes sense. But I used the default value of `MAX_CONTEXTS`, which is 200 and `MAX_DATA_CONTEXTS`, which is 1000. I checked my 'data.train.c2s', every context is padded to length of 1000. I am not sure what is the reason.

I still think the reason is the dict, because it works whenever I use your dict. The way I create dict is just dumping three histograms and the numbers (same with preprocess.py).

Thank you very much!

**Comment by urialon** [comment]
Let's compare the dict files.

Please run the following code separately on the two dictionary files, changing `DICT_FILE_PATH` every time:

```
with open('{}.dict.c2s'.format(DICT_FILE_PATH, 'rb') as file:
                subtoken_to_count = pickle.load(file)
                node_to_count = pickle.load(file)
                target_to_count = pickle.load(file)
                max_contexts = pickle.load(file)
                self.num_training_examples = pickle.load(file)
                print('Dictionaries loaded.')
```

what is `max_contexts` in each case?

**Comment by urialon** [comment]
Also note that `self.config.DATA_NUM_CONTEXTS` needs to be `0` such that the value of `max_contexts` from the dict file will be loaded:
https://github.com/tech-srl/code2seq/blob/master/model.py#L42

**Comment by JiyangZhang** [comment]
Sweet! I found that I dumped `max_contexts` rather than `max_data_contexts`  into dictionary. Now it successfully reading the data.

Thank you very much.
