### ISSUE TITLE
Potential bug: when calculating rouge

### ISSUE THREAD

**Issue by JiyangZhang** [tech-srl/code2seq#48]
When the model evaluate, calculating rouge score, I came across the following exceptions:

`Traceback (most recent call last):
  File "code2seq.py", line 41, in <module>
    model.train()
  File "model.py", line 101, in train
    results, precision, recall, f1, rouge = self.evaluate()
  File "model.py", line 241, in evaluate
    rouge = files_rouge.get_scores(hyp_path=predicted_file_name, ref_path=ref_file_name, avg=True, ignore_empty=True)
  File "lib/python3.7/site-packages/rouge/rouge.py", line 47, in get_scores
    ignore_empty=ignore_empty)
  File "lib/python3.7/site-packages/rouge/rouge.py", line 98, in get_scores
    hyps, refs = zip(*hyps_and_refs)
`

After I checked the pre_file and ref_file, I found that the all the model's outputs are 'PAD' tokens which are space I think. If the pred file was blank lines, the  files_rouge.get_scores would throw following exceptions. 
Not sure I am correct.

**Comment by urialon** [comment]
Hi @JiyangZhang ,
Thank you for reporting this.
Can you please copy the full exception traceback?
It seems like some details are missing, e.g., which exception was thrown and why.

Thanks,
Uri

**Comment by JiyangZhang** [comment]
Hi @urialon 
I will try to reproduce the exception and update!
I am currently doing comment generation using Code2Seq.
Is there any suggestion for hyper-param or model settings for comment generation? Because I came across some weird things such as all 'PAD' predictions, and NAN loss.

Thanks!

**Comment by urialon** [comment]
Hi @JiyangZhang ,

Regarding "all PAD" - is it possible that there are blank target sequences in the dataset?

Regarding hyperparameters - see whether this helps: #45 

Regarding NaN loss - that's weird and not supposed to happen. Did you change anything in the code? The only difference is the new data? This also might hint to empty targets.

**Comment by urialon** [comment]
Closing due to inactivity, feel free to re-open if you have further questions!
