### ISSUE TITLE
It is possible to do transfer learning?

### ISSUE THREAD

**Issue by jonathansantilli** [tech-srl/code2seq#66]
Hello, fantastic work! amazing, really!

The issue's title pretty much says everything. I would like to know if it is possible to do transfer learning to perform another task for which there are not many examples.

Thanks a lot in advance.

**Comment by urialon** [comment]
Hi,
Thank you for your interest in code2seq and for your kind words!

I haven't tried, and it probably requires some tuning, but I definitely think that it's possible to do transfer learning.
Let me know how it goes!

**Comment by jonathansantilli** [comment]
Hello @urialon thanks for the reply,

that's fantastic news, I was wondering if you already have some guidance prepared to achieve that, something that could allow me to narrow the places in the code that need the tuning you mention.

I would really appreciate any kind of guidance,

Cheers!

**Comment by urialon** [comment]
Hi Jonathan,
I don't think that changing the code is required.

Download the trained model (
https://github.com/tech-srl/code2seq#downloading-a-trained-model-that-can-be-further-trained-270-mb
)
and just continue training it on another dataset.

To continue training, use the same command line as in training (
https://github.com/tech-srl/code2seq/blob/master/train.sh#L17 ), but also
add the `--load path/to/my/model` flag as in:
https://github.com/tech-srl/code2seq#step-3-evaluating-a-trained-model

Cheers,
Uri

**Comment by jonathansantilli** [comment]
That's terrific! thanks a lot for your prompt reply @urialon 
Stay safe!

**Comment by jonathansantilli** [comment]
@urialon it is safe to assume that the `java-large-trainable.tar.gz` trainable model, was trained or started the training process with the default parameters contained on the scripts?

**Comment by urialon** [comment]
Yes

**Comment by urialon** [comment]
Closing due to inactivity, feel free to re-open.

**Comment by jonathansantilli** [comment]
Hello @urialon 
I have tried to keep training with my dataset the [java-large-trainable](https://code2seq.s3.amazonaws.com/model/java-large/java-large-trainable.tar.gz).

Does this error rings a bell to you? (I have reduced the output a little bit):
```
Initalized variables
W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key model/model/SUBTOKENS_VOCAB/Momentum not found in checkpoint
Traceback (most recent call last):
  File "/home/jonathansantilli/.local/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  ...
[[{{node model/save/RestoreV2}}]]

Original stack trace for 'model/save/RestoreV2':
  File "code2seq.py", line 39, in <module>
    model.train()
  File "/xxxxxyyy/code2seq/model.py", line 78, in train
    optimizer, train_loss = self.build_training_graph(self.queue_thread.get_output())
  File "/xxxxxyyy/code2seq/model.py", line 399, in build_training_graph
    self.saver = tf.train.Saver(max_to_keep=10)
  ...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2seq.py", line 39, in <module>
    model.train()
  ...
  File "/home/jonathansantilli/.local/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py", line 1306, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key model/model/SUBTOKENS_VOCAB/Momentum not found in checkpoint
	 [[node model/save/RestoreV2 (defined at /home/jonathansantilli/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'model/save/RestoreV2':
  File "code2seq.py", line 39, in <module>
    model.train()
  File "/xxxxxyyy/code2seq/model.py", line 78, in train
    optimizer, train_loss = self.build_training_graph(self.queue_thread.get_output())
  File "/xxxxxyyy/code2seq/model.py", line 399, in build_training_graph
    self.saver = tf.train.Saver(max_to_keep=10)
```

Command used (modified the `train.sh`):
```
python3 -u code2seq.py --load models/java-large-trainable/saved_model_iter52 --data ${data} --test ${test_data} --save_prefix ${model_dir}/model
```

**Comment by urialon** [comment]
It looks like `Key model/model/SUBTOKENS_VOCAB/Momentum not found in checkpoint`

So it seems that this model was trained with Adam.
Set: `config.USE_MOMENTUM = False` here: https://github.com/tech-srl/code2seq/blob/master/config.py#L28

Best,
Uri

**Comment by jonathansantilli** [comment]
Thanks for the reply @urialon 

I have changed the varaible to `False`, now am facing another different error:

```
Initalized variables
2020-09-24 08:37:38.540951: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key model/beta1_power not found in checkpoint
...
Key model/beta1_power not found in checkpoint
	 [[node model/save/RestoreV2 (defined at /home/jonathansantilli/.local/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
```

I did try to check the options if there was a value I can change, but not sure about it.

Cheers!

**Comment by urialon** [comment]
What are your tensorflow and python versions?

**Comment by jonathansantilli** [comment]
Thanks for the reply @urialon 
`Python: 3.6.9`
`Tensorflow: 1.15.4`

**Comment by urialon** [comment]
Hi @jonathansantilli ,
Yes, you are right, there is something wrong with that saved model.
I just removed it from the README.

You can do one of the following:
1. Train a model from scratch on Java-large, and fine-tune it on another dataset.
2. Continue training this model, using a new optimizer. To do that, you'll need to perform a minor modification in the code.
Instead of [creating the optimizer inside `build_training_graph`](https://github.com/tech-srl/code2seq/blob/master/model.py#L78) and [loading its weights later](https://github.com/tech-srl/code2seq/blob/master/model.py#L85), cut the [lines that create the optimizer](https://github.com/tech-srl/code2seq/blob/master/model.py#L386-L397) and paste them after the loading of weights.

This way, it will only load the weights of the model, and the optimizer will be initialized without loading.
This solution applies also for the standard model (the one that is not specified as "trainable").

Best,
Uri

**Comment by jonathansantilli** [comment]
Thanks for getting back to me @urialon 
I started to train a model with `java-large` but was taking to long. So, I moved to `java-small` and after 21 iterations I got the same results as in the paper (including my own dataset).

I will try the second option you suggest since would be great to verify the results using the weights from the `java-large` model.

Cheers!

**Comment by devGichanLee** [comment]
@urialon Hi. Thank you for your gorgeous work! I'm trying to use this code2vec pretrained model for transfer learning to do binary-classification with 2300 java class. I'm guessing that the model used by @jonathansantilli isn't available now(I downloaded the java-large-model but there isn't). do you have any guideline for transfer learning? Thank you.

**Comment by urialon** [comment]
Hi @devGichanLee ,
Thank you for your interest in our work.
The model **is** available (you can find it in the history of the README file), but it doesn't provide anything that the java-large model is not providing.

What do you think about the [two options that I suggested above](https://github.com/tech-srl/code2seq/issues/66#issuecomment-703203977)?

**Comment by devGichanLee** [comment]
@urialon Thank you for your kind reply. I got the link from previous version of README for trainable model. Could I just follow this https://github.com/tech-srl/code2seq/issues/66#issuecomment-669835663? 
I mean that,
> download java-large-trainable model
> python3 -u code2seq.py --data ${data} --test ${test_data} --save_prefix ${model_dir}/model (setting with load option & my dataset)

**Comment by urialon** [comment]
Please read the entire thread

**Comment by devGichanLee** [comment]
@urialon Thank you. I read it all. but I still don't know 'how to prepare my dataset for training' (T/F assigning?). I'm gonna read other issues for hint. thank you.

**Comment by urialon** [comment]
You can ask me as well.
It's just that your previous question was already answered on the same
thread.
Regarding preparing the dataset, see:
https://github.com/tech-srl/code2seq/#extending-to-other-languages

And you can also download a preprocessed dataset and print the first line
to see the format.
Additionally, you can preprocess a toy dataset using the script:
https://github.com/tech-srl/code2seq/blob/master/preprocess.sh
but run the script step-by-step, to see the intermediate results.

Best,
Uri
