### ISSUE TITLE
Some errors about your code2seq in tf-nightly-gpu

### ISSUE THREAD

**Issue by lishi0927** [tech-srl/code2seq#77]
Recently, I try your codes of TensorFlow 2 version (https://github.com/Kolkir/code2seq) in the tf-nightly-gpu, but it produces some errors. Could you give some advice to fix these bugs.

```
WARNING:tensorflow:AutoGraph could not transform <bound method Reader.process_dataset of <reader.Reader object at 0x7f7dd9359670>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 447, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 239, in initial_analysis
    node = qual_names.resolve(node)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 252, in resolve
    return QnResolver().visit(node)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 447, in generic_visit
    value = self.visit(value)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/ast.py", line 456, in generic_visit
    new_node = self.visit(old_value)
  File "/usr/lib/python3.8/ast.py", line 371, in visit
    return visitor(node)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/qual_names.py", line 232, in visit_Subscript
    if not isinstance(s, gast.Index):
AttributeError: module 'gast' has no attribute 'Index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "code2seq.py", line 29, in <module>
    model.train()
  File "/home/lishi/code2seq-master_v2/modelrunner.py", line 76, in train
    dataset = self.train_dataset_reader.get_dataset()
  File "/home/lishi/code2seq-master_v2/reader.py", line 189, in get_dataset
    self.init_dataset()
  File "/home/lishi/code2seq-master_v2/reader.py", line 199, in init_dataset
    self.dataset = self.dataset \
  File "/usr/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1807, in map
    return ParallelMapDataset(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4242, in __init__
    self._map_func = StructuredFunctionWrapper(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3525, in __init__
    self._function = wrapper_fn.get_concrete_function()
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3057, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3025, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3367, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3202, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3518, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 3453, in _wrapper_helper
    ret = autograph.tf_convert(func, ag_ctx)(*nested_args)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 667, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 454, in converted_call
    return _fall_back_unconverted(f, args, kwargs, options, e)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 501, in _fall_back_unconverted
    return _call_unconverted(f, args, kwargs, options)
  File "/usr/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 478, in _call_unconverted
    return f(*args, **kwargs)
  File "/home/lishi/code2seq-master_v2/reader.py", line 145, in process_dataset
    if self.config.MAX_PATH_LENGTH < sparse_split_path.dense_shape[1]:
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 885, in __bool__
    self._disallow_bool_casting()
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 492, in _disallow_bool_casting
    self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
  File "/usr/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 479, in _disallow_in_graph_mode
    raise errors.OperatorNotAllowedInGraphError(
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function
```

**Comment by urialon** [comment]
Hi @lishi0927 ,
Our code is currently written in TensorFlow 1, so I would expect that TF2 won't work.

Best,
Uri

**Comment by urialon** [comment]
Closing due to inactivity, feel free to re-open if there are any more questions.
